title: Appunti di sviluppo web
permalink: /:title/
baseurl: ""

external_links: [
    ['http://venezia86.it', 'venezia86.it'],
    ['https://simonini.github.io/', 'simonini.github.io'],
    ['https://github.com/rubynetti/blog', 'github.com/rubynetti/blog']
  ]

markdown: kramdown
theme: teatro-vecchio

languages: ['it','en']
google_analytics_account: UA-440601-20
url: "https://simonini.github.io" # the base hostname & protocol for your site
